/* vi: set ts=4 sw=4 et : */
/* vim: set comments= cinoptions=\:0,t0,+8,c4,C1 : */

static const testcase_t testcases[] = {
    {
        .desc = "Simple XML in UTF-8, with BOM",
        .input = "simple-utf8.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-8, without BOM",
        .input = "simple-utf8.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16BE, with BOM",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16LE, with BOM",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16LE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16BE, invalid transport encoding",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .transport_encoding = "INVALID_ENCODING",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("simple-utf16.xml", 1, 0),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Unsupported encoding 'INVALID_ENCODING'",
            ),
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in invalid encoding",
        .input = "simple-invalid-encoding.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("simple-invalid-encoding.xml", 1, 151),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Unsupported encoding 'INVALID_ENCODING_WITH_A_VERY_LONG_NAME_THAT_IS_GOING_TO_SPAN_A_FEW_LINES_AND_PROBABLY_REQUIRE_REALLOCATION_OF_THE_BUFFER'",
            ),
            E(MESSAGE,
                    .loc = LOC("simple-invalid-encoding.xml", 1, 151),
                    .info = XMLERR_NOTE,
                    .msg = "(encoding from XML declaration)",
            ),
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "INVALID_ENCODING_WITH_A_VERY_LONG_NAME_THAT_IS_GOING_TO_SPAN_A_FEW_LINES_AND_PROBABLY_REQUIRE_REALLOCATION_OF_THE_BUFFER",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            END,
        },
    },
};
