/* vi: set ts=4 sw=4 et : */
/* vim: set comments= cinoptions=\:0,t0,+8,c4,C1 : */

static const testcase_t testcases[] = {
    {
        .desc = "No declaration in UTF-8, with BOM",
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = false,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
                    .initial_encoding = "UTF-8",
            ),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-8, without BOM",
        .input = "simple-no-decl.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = false,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
                    .initial_encoding = "UTF-8",
            ),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-16BE, with BOM",
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = false,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
                    .initial_encoding = "UTF-16BE",
            ),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-16BE, without BOM",
        .input = "simple-no-decl.xml",
        .use_bom = false,
        .encoding = "UTF-16BE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("simple-no-decl.xml", 1, 0),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "UTF-16 encoding without byte-order mark",
            ),
            E(XMLDECL,
                    .has_decl = false,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
                    .initial_encoding = "UTF-16BE",
            ),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-16LE, with BOM",
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .encoding = "UTF-16LE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = false,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
                    .initial_encoding = "UTF-16LE",
            ),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-16LE, without BOM",
        .input = "simple-no-decl.xml",
        .use_bom = false,
        .encoding = "UTF-16LE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("simple-no-decl.xml", 1, 0),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "UTF-16 encoding without byte-order mark",
            ),
            E(XMLDECL,
                    .has_decl = false,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
                    .initial_encoding = "UTF-16LE",
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-8, with BOM",
        .input = "simple-utf8.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
                    .initial_encoding = "UTF-8",
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-8, without BOM",
        .input = "simple-utf8.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
                    .initial_encoding = "UTF-8",
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16BE, with BOM",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
                    .initial_encoding = "UTF-16BE",
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16LE, with BOM",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16LE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
                    .initial_encoding = "UTF-16LE",
            ),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16BE, invalid transport encoding",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .transport_encoding = "INVALID_ENCODING",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("simple-utf16.xml", 1, 0),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Unsupported encoding 'INVALID_ENCODING'",
            ),
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
                    .initial_encoding = "UTF-16BE",
            ),
            END,
        },
    },
    {
        .desc = "Simple XML with invalid encoding declaration",
        .input = "simple-invalid-encoding.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("simple-invalid-encoding.xml", 1, 151),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Unsupported encoding 'INVALID_ENCODING_WITH_A_VERY_LONG_NAME_THAT_IS_GOING_TO_SPAN_A_FEW_LINES_AND_PROBABLY_REQUIRE_REALLOCATION_OF_THE_BUFFER'",
            ),
            E(MESSAGE,
                    .loc = LOC("simple-invalid-encoding.xml", 1, 151),
                    .info = XMLERR_NOTE,
                    .msg = "(encoding from XML declaration)",
            ),
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "INVALID_ENCODING_WITH_A_VERY_LONG_NAME_THAT_IS_GOING_TO_SPAN_A_FEW_LINES_AND_PROBABLY_REQUIRE_REALLOCATION_OF_THE_BUFFER",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
                    .initial_encoding = "UTF-8",
            ),
            END,
        },
    },
    {
        .desc = "Incompatible encodings from transport layer and from autodetection",
        .input = "simple-utf8.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = "UTF-16BE",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("simple-utf8.xml", 1, 0),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Incompatible encodings: 'UTF-16BE' and 'UTF-8'",
            ),
            E(MESSAGE,
                    .loc = LOC("simple-utf8.xml", 1, 0),
                    .info = XMLERR_NOTE,
                    .msg = "(autodetected from Byte-order Mark)",
            ),
            END,
        },
    },
    {
        .desc = "Incompatible encodings from autodetection and from declaration",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("simple-utf16.xml", 1, 37),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Incompatible encodings: 'UTF-8' and 'UTF-16'",
            ),
            E(MESSAGE,
                    .loc = LOC("simple-utf16.xml", 1, 37),
                    .info = XMLERR_NOTE,
                    .msg = "(encoding from XML declaration)",
            ),
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
                    .initial_encoding = "UTF-8",
            ),
            END,
        },
    },
    {
        .desc = "Truncated declaration #1",
        .input = "truncated-decl1.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("truncated-decl1.xml", 1, 24),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "XMLDecl truncated",
            ),
            END,
        },
    },
    {
        .desc = "Truncated declaration #2",
        .input = "truncated-decl2.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("truncated-decl2.xml", 1, 34),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "XMLDecl truncated",
            ),
            END,
        },
    },
    {
        .desc = "Truncated declaration #3",
        .input = "truncated-decl3.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("truncated-decl3.xml", 1, 38),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "XMLDecl truncated",
            ),
            END,
        },
    },
    {
        .desc = "Non-ASCII character in declaration",
        .input = "nonascii-decl.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("nonascii-decl.xml", 4, 2),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "XMLDecl contains non-ASCII characters",
            ),
            END,
        },
    },
    {
        .desc = "No mandatory attribute #1",
        .input = "decl-no-version1.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("decl-no-version1.xml", 1, 8),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO,
                    .version = XML_INFO_VERSION_NO_VALUE,
                    .initial_encoding = "UTF-8",
            ),
            END,
        },
    },
    {
        .desc = "No mandatory attribute #2",
        .input = "decl-no-version2.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("decl-no-version2.xml", 1, 8),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(XMLDECL,
                    .has_decl = true,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
                    .initial_encoding = "UTF-8",
            ),
            END,
        },
    },
    {
        .desc = "Wrong order of pseudo-attributes",
        .input = "decl-wrong-order.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE,
                    .loc = LOC("decl-wrong-order.xml", 1, 8),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(MESSAGE,
                    .loc = LOC("decl-wrong-order.xml", 1, 25),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            END,
        },
    },
};
