/* vi: set ts=4 sw=4 et : */
/* vim: set comments= cinoptions=\:0,t0,+8,c4,C1 : */

/**
    Tests for XMLDecl conditions all use dummy <a/> element as document
    content.
*/
#define E_XMLDECL_A(s, l, p) \
        E(STAG, LOC(s, l, p), \
                .type = "a", \
                .typelen = 1, \
                .parent = NULL, \
                .baton = NULL, \
        ), \
        E(ETAG, LOC(s, l, p), \
                .type = "a", \
                .typelen = 1, \
                .baton = NULL, \
                .is_empty = true, \
        )

static const testcase_t testcases_encoding[] = {
    {
        .desc = "No declaration in UTF-8, with BOM",
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E_XMLDECL_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-8, without BOM",
        .input = "simple-no-decl.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E_XMLDECL_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-16BE, with BOM",
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, no encoding in "
                    "XMLDecl, content in UTF-16BE encoding",
            ),
            E_XMLDECL_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-16BE, without BOM",
        .input = "simple-no-decl.xml",
        .use_bom = false,
        .encoding = "UTF-16BE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, no encoding "
                    "in XMLDecl, content in UTF-16BE encoding",
            ),
            E_XMLDECL_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-16LE, with BOM",
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .encoding = "UTF-16LE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, no encoding "
                    "in XMLDecl, content in UTF-16LE encoding",
            ),
            E_XMLDECL_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        .desc = "No declaration in UTF-16LE, without BOM",
        .input = "simple-no-decl.xml",
        .use_bom = false,
        .encoding = "UTF-16LE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, no encoding "
                    "in XMLDecl, content in UTF-16LE encoding",
            ),
            E_XMLDECL_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-8, with BOM",
        .input = "simple-utf8.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf8.xml", 1, 1),
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_XMLDECL_A("simple-utf8.xml", 3, 1),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-8, without BOM",
        .input = "simple-utf8.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf8.xml", 1, 1),
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_XMLDECL_A("simple-utf8.xml", 3, 1),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16BE, with BOM",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_XMLDECL_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16LE, with BOM",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16LE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_XMLDECL_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16 (BE), without BOM",
        .input = "simple-utf16.xml",
        .use_bom = false,
        .encoding = "UTF-16BE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "UTF-16 encoding without byte-order mark",
            ),
            E_XMLDECL_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16 (LE), without BOM",
        .input = "simple-utf16.xml",
        .use_bom = false,
        .encoding = "UTF-16LE",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "UTF-16 encoding without byte-order mark",
            ),
            E_XMLDECL_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        .desc = "Simple XML in UTF-16BE, invalid transport encoding",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .transport_encoding = "INVALID_ENCODING",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Unsupported encoding 'INVALID_ENCODING'",
            ),
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_XMLDECL_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        .desc = "Simple XML with invalid encoding declaration",
        .input = "simple-invalid-encoding.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-invalid-encoding.xml", 1, 1),
                    .encoding = "INVALID_ENCODING_WITH_A_VERY_LONG_NAME_THAT"
                    "_IS_GOING_TO_SPAN_A_FEW_LINES_AND_PROBABLY_REQUIRE_"
                    "REALLOCATION_OF_THE_BUFFER",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(MESSAGE, LOC("simple-invalid-encoding.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Unsupported encoding 'INVALID_ENCODING_WITH_A_VERY"
                    "_LONG_NAME_THAT_IS_GOING_TO_SPAN_A_FEW_LINES_AND_PROBABLY"
                    "_REQUIRE_REALLOCATION_OF_THE_BUFFER'",
            ),
            E(MESSAGE, LOC("simple-invalid-encoding.xml", 1, 1),
                    .info = XMLERR_NOTE,
                    .msg = "(encoding from XML declaration)",
            ),
            E_XMLDECL_A("simple-invalid-encoding.xml", 2, 1),
            END,
        },
    },
    {
        .desc = "Incompatible encodings from transport layer and from autodetection",
        .input = "simple-utf8.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = "UTF-16BE",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-utf8.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Incompatible encodings: 'UTF-16BE' and 'UTF-8'",
            ),
            E(MESSAGE, LOC("simple-utf8.xml", 1, 1),
                    .info = XMLERR_NOTE,
                    .msg = "(autodetected from Byte-order Mark)",
            ),
            END,
        },
    },
    {
        .desc = "Incompatible encodings from autodetection and from declaration",
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Incompatible encodings: 'UTF-8' and 'UTF-16'",
            ),
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    .info = XMLERR_NOTE,
                    .msg = "(encoding from XML declaration)",
            ),
            E_XMLDECL_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        .desc = "Partial character at end of input",
        .input = "partial-chars.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_XMLDECL_A("partial-chars.xml", 1, 1),
            E(MESSAGE, LOC("partial-chars.xml", 3, 2),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Partial characters at end of input",
            ),
            END,
        },
    },
    {
        .desc = "Invalid character at top level",
        .input = "invalid-chars-top-level.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_XMLDECL_A("invalid-chars-top-level.xml", 1, 1),
            E(MESSAGE, LOC("invalid-chars-top-level.xml", 1, 5),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Invalid content at root level",
            ),
            END,
        },
    },
};

static const testcase_t testcases_xmldecl[] = {
    {
        .desc = "Truncated declaration #1",
        .input = "truncated-decl1.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("truncated-decl1.xml", 1, 21),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            E(MESSAGE, LOC("truncated-decl1.xml", 1, 25),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '='",
            ),
            E(MESSAGE, LOC("truncated-decl1.xml", 1, 25),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        .desc = "Truncated declaration #2",
        .input = "truncated-decl2.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("truncated-decl2.xml", 1, 30),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unterminated literal",
            ),
            E(MESSAGE, LOC("truncated-decl2.xml", 1, 35),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        .desc = "Truncated declaration #3",
        .input = "truncated-decl3.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("truncated-decl3.xml", 1, 38),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '?>'",
            ),
            E(MESSAGE, LOC("truncated-decl3.xml", 1, 39),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        .desc = "Non-ASCII character in declaration",
        .input = "nonascii-decl.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("nonascii-decl.xml", 4, 9),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Non-ASCII characters in XMLDecl",
            ),
            E(MESSAGE, LOC("nonascii-decl.xml", 4, 9),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            E(XMLDECL, LOC("nonascii-decl.xml", 1, 1),
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_YES,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E_XMLDECL_A("nonascii-decl.xml", 5, 1),
            END,
        },
    },
    {
        .desc = "No mandatory attribute #1",
        .input = "decl-no-version1.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-version1.xml", 1, 7),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(XMLDECL, LOC("decl-no-version1.xml", 1, 1),
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_XMLDECL_A("decl-no-version1.xml", 1, 41),
            END,
        },
    },
    {
        .desc = "No mandatory attribute #2",
        .input = "decl-no-version2.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-version2.xml", 1, 7),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(XMLDECL, LOC("decl-no-version2.xml", 1, 1),
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_XMLDECL_A("decl-no-version2.xml", 1, 9),
            END,
        },
    },
    {
        .desc = "Wrong order of pseudo-attributes",
        .input = "decl-wrong-order.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-wrong-order.xml", 1, 7),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(MESSAGE, LOC("decl-wrong-order.xml", 1, 24),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            E(XMLDECL, LOC("decl-wrong-order.xml", 1, 1),
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_XMLDECL_A("decl-wrong-order.xml", 1, 39),
            END,
        },
    },
    {
        .desc = "Extra pseudo-attribute at the end",
        .input = "decl-extra-attr1.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-extra-attr1.xml", 1, 55),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            E(XMLDECL, LOC("decl-extra-attr1.xml", 1, 1),
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_YES,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_XMLDECL_A("decl-extra-attr1.xml", 1, 70),
            END,
        },
    },
    {
        .desc = "Malformed declaration #1",
        .input = "decl-malformed1.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-malformed1.xml", 1, 20),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '?>'",
            ),
            E(MESSAGE, LOC("decl-malformed1.xml", 1, 21),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        .desc = "Pseudo-attribute without = #1",
        .input = "decl-no-equal1.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-equal1.xml", 1, 29),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '='",
            ),
            E(MESSAGE, LOC("decl-no-equal1.xml", 1, 29),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        .desc = "Pseudo-attribute without = #2",
        .input = "decl-no-equal2.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-equal2.xml", 1, 14),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '='",
            ),
            E(MESSAGE, LOC("decl-no-equal2.xml", 1, 14),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        .desc = "Pseudo-attribute without quotes",
        .input = "decl-no-quote.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-quote.xml", 1, 32),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Quoted literal expected",
            ),
            E(MESSAGE, LOC("decl-no-quote.xml", 1, 32),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        .desc = "Future XML 1.x version",
        .input = "decl-xml-1.2.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-xml-1.2.xml", 1, 15),
                    .info = XMLERR(WARN, XML, FUTURE_VERSION),
                    .msg = "Document specifies unknown 1.x XML version",
            ),
            E(XMLDECL, LOC("decl-xml-1.2.xml", 1, 1),
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_XMLDECL_A("decl-xml-1.2.xml", 1, 22),
            END,
        },
    },
    {
        .desc = "Unsupported XML version",
        .input = "decl-xml-2.0.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-xml-2.0.xml", 1, 15),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unsupported XML version",
            ),
            E(XMLDECL, LOC("decl-xml-2.0.xml", 1, 1),
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_XMLDECL_A("decl-xml-2.0.xml", 1, 22),
            END,
        },
    },
    {
        .desc = "Invalid encoding value",
        .input = "decl-invalid-encoding.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-invalid-encoding.xml", 1, 30),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Invalid encoding name",
            ),
            E(XMLDECL, LOC("decl-invalid-encoding.xml", 1, 1),
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E_XMLDECL_A("decl-invalid-encoding.xml", 1, 37),
            END,
        },
    },
    {
        .desc = "Invalid standalone value",
        .input = "decl-invalid-standalone.xml",
        .use_bom = true,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-invalid-standalone.xml", 1, 32),
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unsupported standalone status",
            ),
            E(XMLDECL, LOC("decl-invalid-standalone.xml", 1, 1),
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_XMLDECL_A("decl-invalid-standalone.xml", 1, 41),
            END,
        },
    },
    {
        .desc = "Document with no declaration in non-UTF8/UTF16 encoding",
        .input = "simple-no-decl.xml",
        .use_bom = false,
        .encoding = "IBM037",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, "
                    "no encoding in XMLDecl, content in IBM500 encoding",
            ),
            E_XMLDECL_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        .desc = "Document with no declaration in non-UTF8/UTF16 encoding "
                "(has transport encoding)",
        .input = "simple-no-decl.xml",
        .use_bom = false,
        .encoding = "IBM037",
        .transport_encoding = "IBM500",
        .events = (const xml_reader_cbparam_t[]){
            E_XMLDECL_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
};

static const testcase_t testcases_element[] = {
    {
        .desc = "Simple opening/closing tags",
        .input = "simple-open-close.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-open-close.xml", 1, 1),
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(STAG, LOC("simple-open-close.xml", 2, 1),
                    .type = "a",
                    .typelen = 1,
                    .parent = NULL,
                    .baton = NULL,
            ),
            E(ETAG, LOC("simple-open-close.xml", 2, 4),
                    .type = "a",
                    .typelen = 1,
                    .baton = NULL,
                    .is_empty = false,
            ),
            END,
        },
    },
    {
        .desc = "Invalid top-level content (no XMLDecl)",
        .input = "invalid-top-level-nodecl.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("invalid-top-level-nodecl.xml", 1, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Invalid content at root level",
            ),
            E(MESSAGE, LOC("invalid-top-level-nodecl.xml", 2, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "No root element",
            ),
            END,
        },
    },
    {
        .desc = "Invalid top-level content (with XMLDecl)",
        .input = "invalid-top-level.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("invalid-top-level.xml", 1, 1),
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E(MESSAGE, LOC("invalid-top-level.xml", 2, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Invalid content at root level",
            ),
            E(MESSAGE, LOC("invalid-top-level.xml", 3, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "No root element",
            ),
            END,
        },
    },
    {
        .desc = "Invalid top-level content (with XMLDecl & root element)",
        .input = "invalid-top-level-withroot.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("invalid-top-level-withroot.xml", 1, 1),
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E(MESSAGE, LOC("invalid-top-level-withroot.xml", 2, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Invalid content at root level",
            ),
            E_XMLDECL_A("invalid-top-level-withroot.xml", 3, 1),
            END,
        },
    },
    {
        .desc = "DTD specified twice",
        .input = "dtd-twice.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("dtd-twice.xml", 2, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Document type definition not allowed here",
            ),
            E_XMLDECL_A("dtd-twice.xml", 3, 1),
            END,
        },
    },
    {
        .desc = "DTD specified after root element",
        .input = "dtd-after-element.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E_XMLDECL_A("dtd-after-element.xml", 1, 1),
            E(MESSAGE, LOC("dtd-after-element.xml", 2, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Document type definition not allowed here",
            ),
            END,
        },
    },
    {
        .desc = "Root element specified twice",
        .input = "root-element-twice.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E_XMLDECL_A("root-element-twice.xml", 1, 1),
            E(MESSAGE, LOC("root-element-twice.xml", 2, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "One root element allowed in a document",
            ),
            E_XMLDECL_A("root-element-twice.xml", 2, 1),
            END,
        },
    },
    {
        .desc = "No root element",
        .input = "no-root-element.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("no-root-element.xml", 1, 1),
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E(MESSAGE, LOC("no-root-element.xml", 4, 1),
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "No root element",
            ),
            END,
        },
    },
    {
        .desc = "Bad element type in empty tag",
        .input = "bad-emptytag-name.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("bad-emptytag-name.xml", 1, 2),
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expected element type",
            ),
            END,
        },
    },
    {
        .desc = "Bad element type in start tag",
        .input = "bad-stag-name.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("bad-stag-name.xml", 1, 2),
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expected element type",
            ),
            END,
        },
    },
    {
        .desc = "Truncated start tag",
        .input = "truncated-stag.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("truncated-stag.xml", 1, 1),
                    .type = "a",
                    .typelen = 1,
                    .parent = NULL,
                    .baton = NULL
            ),
            E(MESSAGE, LOC("truncated-stag.xml", 2, 1),
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Element start tag truncated",
            ),
            END,
        },
    },
    {
        .desc = "Bad character in start tag #1",
        .input = "stag-badchar1.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("stag-badchar1.xml", 1, 1),
                    .type = "element",
                    .typelen = 7,
                    .parent = NULL,
                    .baton = NULL
            ),
            E(MESSAGE, LOC("stag-badchar1.xml", 1, 9),
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expect whitespace, or >, or />",
            ),
            END,
        },
    },
    {
        .desc = "Bad character in start tag #2",
        .input = "stag-badchar2.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("stag-badchar2.xml", 1, 1),
                    .type = "element",
                    .typelen = 7,
                    .parent = NULL,
                    .baton = NULL
            ),
            E(MESSAGE, LOC("stag-badchar2.xml", 1, 10),
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expect whitespace, or >, or />",
            ),
            END,
        },
    },
    {
        .desc = "No name in end tag",
        .input = "etag-noname.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("etag-noname.xml", 1, 1),
                    .type = "a",
                    .typelen = 1,
                    .parent = NULL,
                    .baton = NULL
            ),
            E(MESSAGE, LOC("etag-noname.xml", 1, 6),
                    .info = XMLERR(ERROR, XML, P_ETag),
                    .msg = "Expected element type",
            ),
            END,
        },
    },
    {
        .desc = "Bad name in end tag",
        .input = "etag-badname.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("etag-badname.xml", 1, 1),
                    .type = "a",
                    .typelen = 1,
                    .parent = NULL,
                    .baton = NULL
            ),
            E(MESSAGE, LOC("etag-badname.xml", 1, 6),
                    .info = XMLERR(ERROR, XML, P_ETag),
                    .msg = "Expected element type",
            ),
            END,
        },
    },
    {
        .desc = "End tag mismatch to start tag",
        .input = "etag-mismatch.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("etag-mismatch.xml", 1, 1),
                    .type = "a",
                    .typelen = 1,
                    .parent = NULL,
                    .baton = NULL
            ),
            E(MESSAGE, LOC("etag-mismatch.xml", 1, 6),
                    .info = XMLERR(ERROR, XML, WFC_ELEMENT_TYPE_MATCH),
                    .msg = "Closing element type mismatch: 'b'"
            ),
            E(MESSAGE, LOC("etag-mismatch.xml", 1, 2),
                    .info = XMLERR_NOTE,
                    .msg = "Opening element: 'a'",
            ),
            E(ETAG, LOC("etag-mismatch.xml", 1, 4),
                    .type = "b",
                    .typelen = 1,
                    .baton = NULL,
                    .is_empty = false,
            ),
            END,
        },
    },
    {
        .desc = "Missing closing bracket in end tag",
        .input = "etag-missing-bracket.xml",
        .use_bom = false,
        .encoding = "UTF-8",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("etag-missing-bracket.xml", 1, 1),
                    .type = "a",
                    .typelen = 1,
                    .parent = NULL,
                    .baton = NULL
            ),
            E(ETAG, LOC("etag-missing-bracket.xml", 1, 4),
                    .type = "a",
                    .typelen = 1,
                    .baton = NULL,
                    .is_empty = false,
            ),
            E(MESSAGE, LOC("etag-missing-bracket.xml", 2, 1),
                    .info = XMLERR(ERROR, XML, P_ETag),
                    .msg = "Expected string: '>'",
            ),
            END,
        },
    },
    {
        .desc = "Element immediately following XMLDecl in non-ASCII",
        .input = "element-nonutf8-name.xml",
        .use_bom = false,
        .encoding = "ISO-8859-1",
        .transport_encoding = NULL,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("element-nonutf8-name.xml", 1, 1),
                    .encoding = "ISO-8859-1",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(STAG, LOC("element-nonutf8-name.xml", 1, 44),
                    .type = "é",
                    .typelen = 2,
                    .parent = NULL,
                    .baton = NULL
            ),
            E(ETAG, LOC("element-nonutf8-name.xml", 1, 47),
                    .type = "é",
                    .typelen = 2,
                    .baton = NULL,
                    .is_empty = false,
            ),
            END,
        },
    },
};

static const testset_t testset[] = {
    {
        .desc = "Encoding tests",
        .func = run_testcase,
        .cases = testcases_encoding,
        .size = sizeof(testcase_t),
        .ncases = sizeofarray(testcases_encoding),
    },
    {
        .desc = "XML/Text declaration tests",
        .func = run_testcase,
        .cases = testcases_xmldecl,
        .size = sizeof(testcase_t),
        .ncases = sizeofarray(testcases_xmldecl),
    },
    {
        .desc = "Element tests",
        .func = run_testcase,
        .cases = testcases_element,
        .size = sizeof(testcase_t),
        .ncases = sizeofarray(testcases_element),
    },
};

static const testsuite_t testsuite = TEST_SUITE("Tests for XML reader API", testset);

