/* vi: set ts=4 sw=4 et : */
/* vim: set comments= cinoptions=\:0,t0,+8,c4,C1 : */

static result_t
set_reader_options_pre(xml_reader_t *h, const void *arg)
{
    if (!xml_reader_set_transport_encoding(h, "UTF-8")) {
        printf("Failed to set transport encoding\n");
        return FAIL;
    }
    if (!xml_reader_set_normalization(h, XML_READER_NORM_OFF)) {
        printf("Failed to disable normalization checks\n");
        return FAIL;
    }
    if (!xml_reader_set_location_tracking(h, true, 4)) {
        printf("Failed to configure tabstop size to 4\n");
        return FAIL;
    }
    printf("Pre-parsing configuration set\n");
    return PASS;
}

static result_t
set_reader_options_post(xml_reader_t *h, xml_reader_cbparam_t *e, const void *arg)
{
    if (e->cbtype == XML_READER_CB_XMLDECL) {
        if (xml_reader_set_transport_encoding(h, "UTF-8")) {
            printf("Succeeded to set transport encoding\n");
            return FAIL;
        }
        if (xml_reader_set_normalization(h, XML_READER_NORM_ON)) {
            printf("Succeeded to disable normalization checks\n");
            return FAIL;
        }
        if (xml_reader_set_location_tracking(h, true, 2)) {
            printf("Succeeded to configure tabstop size to 2\n");
            return FAIL;
        }
        printf("Configuration immutable during parsing.\n");
    }
    else if (e->cbtype == XML_READER_CB_STAG) {
        xml_reader_set_callback(h, NULL, NULL);
    }
    return PASS;
}

static result_t
disable_location_tracking(xml_reader_t *h, const void *arg)
{
    if (!xml_reader_set_location_tracking(h, false, 0)) {
        printf("Failed to disable location tracking\n");
        return FAIL;
    }
    return PASS;
}

static const testcase_t testcases_api[] = {
    {
        TC("Setting reader options before/after parsing start"),
        .input = "simple-utf8.xml",
        .pretest = set_reader_options_pre,
        .checkevt = set_reader_options_post,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf8.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(STAG, LOC("simple-utf8.xml", 3, 5), TOK("a")),
            END,
        },
    },
    {
        TC("Disable location tracking"),
        .input = "simple-utf8.xml",
        .pretest = disable_location_tracking,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf8.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(STAG, LOC("simple-utf8.xml", 1, 1), TOK("a")),
            E(STAG_END, LOC("simple-utf8.xml", 1, 1),
                    NOTOK,
                    .is_empty = true,
            ),
            END,
        },
    },
};

/**
    Tests for XMLDecl conditions all use dummy \<a/> element as document
    content.
*/
#define E_EMPTY_A(s, l, p) \
        E(STAG, LOC(s, l, p), TOK("a")), \
        E(STAG_END, LOC(s, l, p + 2), NOTOK, .is_empty = true)

struct test_set_transport_encoding_s {
    const char *enc;
    bool expected;
};

static result_t
test_set_transport_encoding(xml_reader_t *h, const void *arg)
{
    const struct test_set_transport_encoding_s *sts = arg;

    printf("- Setting transport encoding to '%s'\n", sts->enc);
    return xml_reader_set_transport_encoding(h, sts->enc) == sts->expected ?
            PASS : FAIL;
}

#define TEST_TRANSPORT_ENCODING(e, r) \
        .pretest = test_set_transport_encoding, \
        .pretest_arg = &(const struct test_set_transport_encoding_s){ \
            .enc = (e), \
            .expected = (r), \
        },

static const testcase_t testcases_encoding[] = {
    {
        TC("No declaration in UTF-8, with BOM"),
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        TC("No declaration in UTF-8, without BOM"),
        .input = "simple-no-decl.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        TC("No declaration in UTF-16BE, with BOM"),
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, no encoding in "
                    "XMLDecl, content in UTF-16BE encoding",
            ),
            E_EMPTY_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        TC("No declaration in UTF-16BE, without BOM"),
        .input = "simple-no-decl.xml",
        .encoding = "UTF-16BE",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, no encoding "
                    "in XMLDecl, content in UTF-16BE encoding",
            ),
            E_EMPTY_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        TC("No declaration in UTF-16LE, with BOM"),
        .input = "simple-no-decl.xml",
        .use_bom = true,
        .encoding = "UTF-16LE",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, no encoding "
                    "in XMLDecl, content in UTF-16LE encoding",
            ),
            E_EMPTY_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        TC("No declaration in UTF-16LE, without BOM"),
        .input = "simple-no-decl.xml",
        .encoding = "UTF-16LE",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, no encoding "
                    "in XMLDecl, content in UTF-16LE encoding",
            ),
            E_EMPTY_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        TC("Simple XML in UTF-8, with BOM"),
        .input = "simple-utf8.xml",
        .use_bom = true,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf8.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("simple-utf8.xml", 3, 9),
            END,
        },
    },
    {
        TC("Simple XML in UTF-8, without BOM"),
        .input = "simple-utf8.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf8.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("simple-utf8.xml", 3, 9),
            END,
        },
    },
    {
        TC("Simple XML in UTF-16BE, with BOM"),
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        TC("Simple XML in UTF-16LE, with BOM"),
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16LE",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        TC("Simple XML in UTF-16 (BE), without BOM"),
        .input = "simple-utf16.xml",
        .encoding = "UTF-16BE",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "UTF-16 encoding without byte-order mark",
            ),
            E_EMPTY_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        TC("Simple XML in UTF-16 (LE), without BOM"),
        .input = "simple-utf16.xml",
        .encoding = "UTF-16LE",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "UTF-16 encoding without byte-order mark",
            ),
            E_EMPTY_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        TC("Simple XML in UTF-16BE, invalid transport encoding"),
        .input = "simple-utf16.xml",
        .use_bom = true,
        .encoding = "UTF-16BE",
        TEST_TRANSPORT_ENCODING("INVALID_ENCODING", false)
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Unsupported encoding 'INVALID_ENCODING'",
            ),
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        TC("Simple XML with invalid encoding declaration"),
        .input = "simple-invalid-encoding.xml",
        .use_bom = true,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-invalid-encoding.xml", 1, 1),
                    NOTOK,
                    .encoding = "INVALID_ENCODING_WITH_A_VERY_LONG_NAME_THAT"
                    "_IS_GOING_TO_SPAN_A_FEW_LINES_AND_PROBABLY_REQUIRE_"
                    "REALLOCATION_OF_THE_BUFFER",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(MESSAGE, LOC("simple-invalid-encoding.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Unsupported encoding 'INVALID_ENCODING_WITH_A_VERY"
                    "_LONG_NAME_THAT_IS_GOING_TO_SPAN_A_FEW_LINES_AND_PROBABLY"
                    "_REQUIRE_REALLOCATION_OF_THE_BUFFER'",
            ),
            E(MESSAGE, LOC("simple-invalid-encoding.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR_NOTE,
                    .msg = "(encoding from XML declaration)",
            ),
            E_EMPTY_A("simple-invalid-encoding.xml", 2, 1),
            END,
        },
    },
    {
        TC("Incompatible encodings from transport layer and from autodetection"),
        .input = "simple-utf8.xml",
        .use_bom = true,
        TEST_TRANSPORT_ENCODING("UTF-16BE", true)
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-utf8.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Incompatible encodings: 'UTF-16BE' and 'UTF-8'",
            ),
            E(MESSAGE, LOC("simple-utf8.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR_NOTE,
                    .msg = "(autodetected from Byte-order Mark)",
            ),
            END,
        },
    },
    {
        TC("Incompatible encodings from autodetection and from declaration"),
        .input = "simple-utf16.xml",
        .use_bom = true,
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-16",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Incompatible encodings: 'UTF-8' and 'UTF-16'",
            ),
            E(MESSAGE, LOC("simple-utf16.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR_NOTE,
                    .msg = "(encoding from XML declaration)",
            ),
            E_EMPTY_A("simple-utf16.xml", 2, 1),
            END,
        },
    },
    {
        TC("Partial character at end of input"),
        .input = "partial-chars.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("partial-chars.xml", 1, 1),
            E(MESSAGE, LOC("partial-chars.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "Partial characters at end of input",
            ),
            END,
        },
    },
    {
        TC("Invalid character at top level"),
        .input = "invalid-chars-top-level.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("invalid-chars-top-level.xml", 1, 1),
            E(MESSAGE, LOC("invalid-chars-top-level.xml", 1, 5),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Invalid content at root level",
            ),
            E(COMMENT, LOC("invalid-chars-top-level.xml", 2, 1),
                    TOK(" Comment ")),
            END,
        },
    },
};

static const testcase_t testcases_xmldecl[] = {
    {
        TC("Truncated declaration #1"),
        .input = "truncated-decl1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("truncated-decl1.xml", 1, 21),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            E(MESSAGE, LOC("truncated-decl1.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '='",
            ),
            E(MESSAGE, LOC("truncated-decl1.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        TC("Truncated declaration #2"),
        .input = "truncated-decl2.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("truncated-decl2.xml", 1, 30),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unterminated literal",
            ),
            E(MESSAGE, LOC("truncated-decl2.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        TC("Truncated declaration #3"),
        .input = "truncated-decl3.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("truncated-decl3.xml", 1, 38),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '?>'",
            ),
            E(MESSAGE, LOC("truncated-decl3.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        TC("Non-ASCII character in declaration"),
        .input = "nonascii-decl.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("nonascii-decl.xml", 4, 9),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Non-ASCII characters in XMLDecl",
            ),
            E(MESSAGE, LOC("nonascii-decl.xml", 4, 9),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            E(XMLDECL, LOC("nonascii-decl.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_YES,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E_EMPTY_A("nonascii-decl.xml", 5, 1),
            END,
        },
    },
    {
        TC("No mandatory attribute #1"),
        .input = "decl-no-version1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-version1.xml", 1, 7),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(XMLDECL, LOC("decl-no-version1.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_EMPTY_A("decl-no-version1.xml", 1, 41),
            END,
        },
    },
    {
        TC("No mandatory attribute #2"),
        .input = "decl-no-version2.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-version2.xml", 1, 7),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(XMLDECL, LOC("decl-no-version2.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_EMPTY_A("decl-no-version2.xml", 1, 9),
            END,
        },
    },
    {
        TC("Wrong order of pseudo-attributes"),
        .input = "decl-wrong-order.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-wrong-order.xml", 1, 7),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Mandatory pseudo-attribute 'version' missing in XMLDecl",
            ),
            E(MESSAGE, LOC("decl-wrong-order.xml", 1, 24),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            E(XMLDECL, LOC("decl-wrong-order.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_EMPTY_A("decl-wrong-order.xml", 1, 39),
            END,
        },
    },
    {
        TC("Extra pseudo-attribute at the end"),
        .input = "decl-extra-attr1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-extra-attr1.xml", 1, 55),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unexpected pseudo-attribute",
            ),
            E(XMLDECL, LOC("decl-extra-attr1.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_YES,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("decl-extra-attr1.xml", 1, 70),
            END,
        },
    },
    {
        TC("Malformed declaration #1"),
        .input = "decl-malformed1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-malformed1.xml", 1, 20),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '?>'",
            ),
            E(MESSAGE, LOC("decl-malformed1.xml", 1, 21),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        TC("Pseudo-attribute without = #1"),
        .input = "decl-no-equal1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-equal1.xml", 1, 29),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '='",
            ),
            E(MESSAGE, LOC("decl-no-equal1.xml", 1, 29),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        TC("Pseudo-attribute without = #2"),
        .input = "decl-no-equal2.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-equal2.xml", 1, 14),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Expected string: '='",
            ),
            E(MESSAGE, LOC("decl-no-equal2.xml", 1, 14),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        TC("Pseudo-attribute without quotes"),
        .input = "decl-no-quote.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-no-quote.xml", 1, 32),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Quoted literal expected",
            ),
            E(MESSAGE, LOC("decl-no-quote.xml", 1, 32),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Malformed XMLDecl",
            ),
            END,
        },
    },
    {
        TC("Future XML 1.x version"),
        .input = "decl-xml-1.2.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-xml-1.2.xml", 1, 15),
                    NOTOK,
                    .info = XMLERR(WARN, XML, FUTURE_VERSION),
                    .msg = "Document specifies unknown 1.x XML version",
            ),
            E(XMLDECL, LOC("decl-xml-1.2.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("decl-xml-1.2.xml", 1, 22),
            END,
        },
    },
    {
        TC("Unsupported XML version #1"),
        .input = "decl-xml-1.A.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-xml-1.A.xml", 1, 15),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unsupported XML version",
            ),
            E(XMLDECL, LOC("decl-xml-1.A.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_EMPTY_A("decl-xml-1.A.xml", 1, 22),
            END,
        },
    },
    {
        TC("Unsupported XML version #2"),
        .input = "decl-xml-2.0.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-xml-2.0.xml", 1, 15),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unsupported XML version",
            ),
            E(XMLDECL, LOC("decl-xml-2.0.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_NO_VALUE,
            ),
            E_EMPTY_A("decl-xml-2.0.xml", 1, 22),
            END,
        },
    },
    {
        TC("Invalid encoding value #1"),
        .input = "decl-invalid-encoding.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-invalid-encoding.xml", 1, 30),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Invalid encoding name",
            ),
            E(XMLDECL, LOC("decl-invalid-encoding.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E_EMPTY_A("decl-invalid-encoding.xml", 1, 37),
            END,
        },
    },
    {
        TC("Invalid encoding value #2"),
        .input = "decl-invalid-encoding2.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-invalid-encoding2.xml", 1, 30),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Invalid encoding name",
            ),
            E(XMLDECL, LOC("decl-invalid-encoding2.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E_EMPTY_A("decl-invalid-encoding2.xml", 1, 41),
            END,
        },
    },
    {
        TC("Invalid standalone value"),
        .input = "decl-invalid-standalone.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("decl-invalid-standalone.xml", 1, 32),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_XMLDecl),
                    .msg = "Unsupported standalone status",
            ),
            E(XMLDECL, LOC("decl-invalid-standalone.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("decl-invalid-standalone.xml", 1, 41),
            END,
        },
    },
    {
        TC("Document with no declaration in non-UTF8/UTF16 encoding"),
        .input = "simple-no-decl.xml",
        .encoding = "IBM037",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("simple-no-decl.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, ENCODING_ERROR),
                    .msg = "No external encoding information, "
                    "no encoding in XMLDecl, content in IBM500 encoding",
            ),
            E_EMPTY_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        .desc = "Document with no declaration in non-UTF8/UTF16 encoding "
                "(has transport encoding)",
        .input = "simple-no-decl.xml",
        .encoding = "IBM037",
        TEST_TRANSPORT_ENCODING("IBM500", true)
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("simple-no-decl.xml", 1, 1),
            END,
        },
    },
    {
        TC("Position updates with combining marks"),
        .input = "combining-mark.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("combining-mark.xml", 1, 1),
                    TOK("a\xCC\x81"),
            ),
            E(STAG_END, LOC("combining-mark.xml", 1, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(ETAG, LOC("combining-mark.xml", 1, 4),
                    TOK("a\xCC\x81"),
            ),
            END,
        },
    },
    {
        TC("NUL/restricted characters in input (1.0)"),
        .input = "nul-restricted-char-1.0.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("nul-restricted-char-1.0.xml", 1, 19),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Char),
                    .msg = "NUL character encountered",
            ),
            E(XMLDECL, LOC("nul-restricted-char-1.0.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E_EMPTY_A("nul-restricted-char-1.0.xml", 2, 1),
            E(MESSAGE, LOC("nul-restricted-char-1.0.xml", 3, 6),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Char),
                    .msg = "Restricted character U+0001",
            ),
            E(MESSAGE, LOC("nul-restricted-char-1.0.xml", 4, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Char),
                    .msg = "Restricted character U+001E",
            ),
            E(COMMENT, LOC("nul-restricted-char-1.0.xml", 3, 1),
                    TOK(" \x01\n\x1E\n\x7F\n\xC2\x9F ")
            ),
            END,
        },
    },
    {
        TC("NUL/restricted characters in input (1.1)"),
        .input = "nul-restricted-char-1.1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("nul-restricted-char-1.1.xml", 1, 19),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Char),
                    .msg = "NUL character encountered",
            ),
            E(XMLDECL, LOC("nul-restricted-char-1.1.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E_EMPTY_A("nul-restricted-char-1.1.xml", 2, 1),
            E(MESSAGE, LOC("nul-restricted-char-1.1.xml", 3, 6),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Char),
                    .msg = "Restricted character U+0001",
            ),
            E(MESSAGE, LOC("nul-restricted-char-1.1.xml", 4, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Char),
                    .msg = "Restricted character U+001E",
            ),
            E(MESSAGE, LOC("nul-restricted-char-1.1.xml", 5, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Char),
                    .msg = "Restricted character U+007F",
            ),
            E(MESSAGE, LOC("nul-restricted-char-1.1.xml", 6, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Char),
                    .msg = "Restricted character U+009F",
            ),
            E(COMMENT, LOC("nul-restricted-char-1.1.xml", 3, 1),
                    TOK(" \x01\n\x1E\n\x7F\n\xC2\x9F "),
            ),
            END,
        },
    },
};

// To avoid defining this monster inline...
#define VERY_LONG_ELEMENT_NAME \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefghabcdefgh" \
        "abcdefgh"


static const testcase_t testcases_structure[] = {
    {
        TC("Simple opening/closing tags"),
        .input = "simple-open-close.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("simple-open-close.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(STAG, LOC("simple-open-close.xml", 2, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("simple-open-close.xml", 2, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(ETAG, LOC("simple-open-close.xml", 2, 4),
                    TOK("a"),
            ),
            END,
        },
    },
    {
        TC("Invalid top-level content (no XMLDecl)"),
        .input = "invalid-top-level-nodecl.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("invalid-top-level-nodecl.xml", 1, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Invalid content at root level",
            ),
            END,
        },
    },
    {
        TC("Invalid top-level content (with XMLDecl)"),
        .input = "invalid-top-level.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("invalid-top-level.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E(MESSAGE, LOC("invalid-top-level.xml", 2, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Invalid content at root level",
            ),
            END,
        },
    },
    {
        TC("Invalid top-level content (with XMLDecl & root element)"),
        .input = "invalid-top-level-withroot.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("invalid-top-level-withroot.xml", 1, 1),
                    NOTOK,
                    .encoding = "UTF-8",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E(MESSAGE, LOC("invalid-top-level-withroot.xml", 2, 1),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_document),
                    .msg = "Invalid content at root level",
            ),
            E_EMPTY_A("invalid-top-level-withroot.xml", 3, 1),
            END,
        },
    },
    {
        // XML reader used to test this condition. Retain until it's
        // implemented in higher DOM/SAX driver
        TC("DTD specified twice"),
        .input = "dtd-twice.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(DTD_BEGIN, LOC("dtd-twice.xml", 1, 1),
                    TOK("a"),
            ),
            E(DTD_END, LOC("dtd-twice.xml", 1, 1),
                    NOTOK,
            ),
            E(DTD_BEGIN, LOC("dtd-twice.xml", 2, 1),
                    TOK("a"),
            ),
            E(DTD_END, LOC("dtd-twice.xml", 2, 1),
                    NOTOK,
            ),
            E_EMPTY_A("dtd-twice.xml", 3, 1),
            END,
        },
    },
    {
        // XML reader used to test this condition. Retain until it's
        // implemented in higher DOM/SAX driver
        TC("DTD specified after root element"),
        .input = "dtd-after-element.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("dtd-after-element.xml", 1, 1),
            E(DTD_BEGIN, LOC("dtd-after-element.xml", 2, 1),
                    TOK("a"),
            ),
            E(DTD_END, LOC("dtd-after-element.xml", 2, 1),
                    NOTOK,
            ),
            END,
        },
    },
    {
        TC("Root element specified twice"),
        .input = "root-element-twice.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("root-element-twice.xml", 1, 1),
            E_EMPTY_A("root-element-twice.xml", 2, 1),
            END,
        },
    },
    {
        TC("No root element"),
        .input = "no-root-element.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("no-root-element.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E(COMMENT, LOC("no-root-element.xml", 3, 1),
                    TOK(" Comment "),
            ),
            END,
        },
    },
    {
        TC("Bad element type in empty tag"),
        .input = "bad-emptytag-name.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("bad-emptytag-name.xml", 1, 2),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expected element type",
            ),
            END,
        },
    },
    {
        TC("Bad element type in start tag"),
        .input = "bad-stag-name.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("bad-stag-name.xml", 1, 2),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expected element type",
            ),
            END,
        },
    },
    {
        TC("Truncated start tag"),
        .input = "truncated-stag.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("truncated-stag.xml", 1, 1),
                    TOK("a"),
            ),
            E(MESSAGE, LOC("truncated-stag.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expect whitespace, or >, or />",
            ),
            END,
        },
    },
    {
        TC("Bad character in start tag #1"),
        .input = "stag-badchar1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("stag-badchar1.xml", 1, 1),
                    TOK("element"),
            ),
            E(MESSAGE, LOC("stag-badchar1.xml", 1, 9),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expect whitespace, or >, or />",
            ),
            END,
        },
    },
    {
        TC("Bad character in start tag #2"),
        .input = "stag-badchar2.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("stag-badchar2.xml", 1, 1),
                    TOK("element"),
            ),
            E(MESSAGE, LOC("stag-badchar2.xml", 1, 10),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_STag),
                    .msg = "Expect whitespace, or >, or />",
            ),
            END,
        },
    },
    {
        TC("No name in end tag"),
        .input = "etag-noname.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("etag-noname.xml", 1, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("etag-noname.xml", 1, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(MESSAGE, LOC("etag-noname.xml", 1, 6),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_ETag),
                    .msg = "Expected element type",
            ),
            E(APPEND, LOC("etag-noname.xml", 1, 7),
                    TOK("\n"),
                    .ws = true,
            ),
            END,
        },
    },
    {
        TC("Bad name in end tag"),
        .input = "etag-badname.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("etag-badname.xml", 1, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("etag-badname.xml", 1, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(MESSAGE, LOC("etag-badname.xml", 1, 6),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_ETag),
                    .msg = "Expected element type",
            ),
            E(APPEND, LOC("etag-badname.xml", 1, 8),
                    TOK("\n"),
                    .ws = true,
            ),
            END,
        },
    },
    {
        TC("End tag mismatch to start tag"),
        .input = "etag-mismatch.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("etag-mismatch.xml", 1, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("etag-mismatch.xml", 1, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(ETAG, LOC("etag-mismatch.xml", 1, 4),
                    TOK("b"),
            ),
            END,
        },
    },
    {
        TC("Missing closing bracket in end tag"),
        .input = "etag-missing-bracket.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("etag-missing-bracket.xml", 1, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("etag-missing-bracket.xml", 1, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(ETAG, LOC("etag-missing-bracket.xml", 1, 4),
                    TOK("a"),
            ),
            E(MESSAGE, LOC("etag-missing-bracket.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_ETag),
                    .msg = "Expected string: '>'",
            ),
            END,
        },
    },
    {
        TC("Element immediately following XMLDecl in non-ASCII"),
        .input = "element-nonutf8-name.xml",
        .encoding = "ISO-8859-1",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("element-nonutf8-name.xml", 1, 1),
                    NOTOK,
                    .encoding = "ISO-8859-1",
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(STAG, LOC("element-nonutf8-name.xml", 1, 44),
                    TOK("é"),
            ),
            E(STAG_END, LOC("element-nonutf8-name.xml", 1, 46),
                    NOTOK,
                    .is_empty = false,
            ),
            E(ETAG, LOC("element-nonutf8-name.xml", 1, 47),
                    TOK("é"),
            ),
            END,
        },
    },
    {
        TC("Comments & Processing instructions"),
        .input = "comments-pis.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(COMMENT, LOC("comments-pis.xml", 1, 1),
                    TOK(" This is a comment "),
            ),
            E(PI_TARGET, LOC("comments-pis.xml", 2, 1),
                    TOK("PI"),
            ),
            E(PI_CONTENT, LOC("comments-pis.xml", 2, 1),
                    TOK("some processing insn"),
            ),
            E_EMPTY_A("comments-pis.xml", 3, 1),
            END,
        },
    },
    {
        TC("Comments & Processing instructions (torture)"),
        .input = "comments-pis-torture.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(MESSAGE, LOC("comments-pis-torture.xml", 1, 23),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Comment),
                    .msg = "Double hyphen must not occur within comments",
            ),
            E(COMMENT, LOC("comments-pis-torture.xml", 1, 1),
                    TOK(" Torture - test -- for --- comments ---- backtracking "),
            ),
            E(PI_TARGET, LOC("comments-pis-torture.xml", 2, 1),
                    TOK("and"),
            ),
            E(PI_CONTENT, LOC("comments-pis-torture.xml", 2, 1),
                    TOK("? for-pis?? of=\"course\""),
            ),
            E(PI_TARGET, LOC("comments-pis-torture.xml", 3, 1),
                    TOK("a"),
            ),
            E(MESSAGE, LOC("comments-pis-torture.xml", 3, 4),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_PI),
                    .msg = "Expected string: '?>'",
            ),
            E(PI_TARGET, LOC("comments-pis-torture.xml", 4, 1),
                    TOK("a"),
            ),
            E(PI_CONTENT, LOC("comments-pis-torture.xml", 4, 1),
                    TOK("???????????????????????????????????"),
            ),
            E(STAG, LOC("comments-pis-torture.xml", 5, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("comments-pis-torture.xml", 5, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(APPEND, LOC("comments-pis-torture.xml", 5, 4),
                    TOK("\n\t"),
                    .ws = true,
            ),
            E(COMMENT, LOC("comments-pis-torture.xml", 6, 9),
                    TOK("<!"),
            ),
            E(APPEND, LOC("comments-pis-torture.xml", 6, 18),
                    TOK("-->\n\t"),
                    .ws = false,
            ),
            E(PI_TARGET, LOC("comments-pis-torture.xml", 7, 9),
                    TOK("pi"),
            ),
            E(APPEND, LOC("comments-pis-torture.xml", 7, 15),
                    TOK("\n\t"),
                    .ws = true,
            ),
            E(COMMENT, LOC("comments-pis-torture.xml", 8, 9),
                    TOK("*-*-*-*"),
            ),
            E(APPEND, LOC("comments-pis-torture.xml", 8, 23),
                    TOK("\n\t"),
                    .ws = true,
            ),
            E(COMMENT, LOC("comments-pis-torture.xml", 9, 9),
                    TOK(""),
            ),
            E(APPEND, LOC("comments-pis-torture.xml", 9, 16),
                    TOK("\n\t"),
                    .ws = true,
            ),
            E(COMMENT, LOC("comments-pis-torture.xml", 10, 9),
                    TOK(" "),
            ),
            E(APPEND, LOC("comments-pis-torture.xml", 10, 17),
                    TOK("\n"),
                    .ws = true,
            ),
            E(ETAG, LOC("comments-pis-torture.xml", 11, 1),
                    TOK("a"),
            ),
            END,
        },
    },
    {
        TC("Unterminated comment"),
        .input = "unterminated-comment.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("unterminated-comment.xml", 1, 1),
            E(MESSAGE, LOC("unterminated-comment.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Comment),
                    .msg = "Unterminated comment",
            ),
            END,
        },
    },
    {
        TC("Unterminated PI #1"),
        .input = "unterminated-pi1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("unterminated-pi1.xml", 1, 1),
            E(PI_TARGET, LOC("unterminated-pi1.xml", 1, 5),
                    TOK("unterminated"),
            ),
            E(MESSAGE, LOC("unterminated-pi1.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_PI),
                    .msg = "Unterminated processing instruction",
            ),
            END,
        },
    },
    {
        TC("Unterminated PI #2"),
        .input = "unterminated-pi2.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("unterminated-pi2.xml", 1, 1),
            E(PI_TARGET, LOC("unterminated-pi2.xml", 1, 5),
                    TOK("unterminated"),
            ),
            E(MESSAGE, LOC("unterminated-pi2.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_PI),
                    .msg = "Expected string: '?>'",
            ),
            END,
        },
    },
    {
        TC("Bad PI target"),
        .input = "pi-badtarget.xml",
        .events = (const xml_reader_cbparam_t[]){
            E_EMPTY_A("pi-badtarget.xml", 1, 1),
            E(MESSAGE, LOC("pi-badtarget.xml", 1, 7),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_PI),
                    .msg = "Expected PI target here",
            ),
            END,
        },
    },
    {
        TC("Very long element name"),
        .input = "very-long-token.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("very-long-token.xml", 1, 1),
                    TOK(VERY_LONG_ELEMENT_NAME),
            ),
            E(STAG_END, LOC("very-long-token.xml", 1, 1034),
                    NOTOK,
                    .is_empty = true,
            ),
            END,
        },
    },
    {
        TC("Attributes"),
        .input = "attributes.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("attributes.xml", 1, 1),
                    TOK("a"),
            ),
            E(ATTR, LOC("attributes.xml", 1, 4),
                    TOK("attr1"),
                    .attrnorm = XML_READER_ATTRNORM_CDATA,
            ),
            E(APPEND, LOC("attributes.xml", 1, 10),
                    TOK("foo"),
                    .ws = false,
            ),
            E(ATTR, LOC("attributes.xml", 1, 16),
                    TOK("attr2"),
                    .attrnorm = XML_READER_ATTRNORM_CDATA,
            ),
            E(APPEND, LOC("attributes.xml", 1, 22),
                    TOK("bar"),
                    .ws = false,
            ),
            E(STAG_END, LOC("attributes.xml", 1, 28),
                    NOTOK,
                    .is_empty = true,
            ),
            END,
        },
    },
    {
        TC("Attributes with char/entity references"),
        .input = "attribute-with-references.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("attribute-with-references.xml", 1, 1),
                    TOK("a"),
            ),
            E(ATTR, LOC("attribute-with-references.xml", 1, 4),
                    TOK("b"),
                    .attrnorm = XML_READER_ATTRNORM_CDATA,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 6),
                    TOK("z"),
                    .ws = false,
            ),
            E(ENTITY_START, LOC("attribute-with-references.xml", 1, 8),
                    TOK("lt"),
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(ENTITY_END, LOC("attribute-with-references.xml", 1, 12),
                    NOTOK,
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("<"),
                    .ws = false,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 12),
                    TOK("y"),
                    .ws = false,
            ),
            E(ENTITY_START, LOC("attribute-with-references.xml", 1, 13),
                    TOK("quot"),
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(ENTITY_END, LOC("attribute-with-references.xml", 1, 19),
                    NOTOK,
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(APPEND, LOC("entity(quot)", 1, 1),
                    TOK("\""),
                    .ws = false,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 19),
                    TOK("x"),
                    .ws = false,
            ),
            E(ENTITY_START, LOC("attribute-with-references.xml", 1, 20),
                    TOK("amp"),
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(ENTITY_END, LOC("attribute-with-references.xml", 1, 25),
                    NOTOK,
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("&"),
                    .ws = false,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 25),
                    TOK("w"),
                    .ws = false,
            ),
            E(ENTITY_START, LOC("attribute-with-references.xml", 1, 26),
                    TOK("gt"),
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(ENTITY_END, LOC("attribute-with-references.xml", 1, 30),
                    NOTOK,
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(APPEND, LOC("entity(gt)", 1, 1),
                    TOK(">"),
                    .ws = false,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 30),
                    TOK("v"),
                    .ws = false,
            ),
            E(ENTITY_START, LOC("attribute-with-references.xml", 1, 31),
                    TOK("apos"),
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(ENTITY_END, LOC("attribute-with-references.xml", 1, 37),
                    NOTOK,
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(APPEND, LOC("entity(apos)", 1, 1),
                    TOK("'"),
                    .ws = false,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 37),
                    TOK("u"),
                    .ws = false,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("\""),
                    .ws = false,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 43),
                    TOK("c"),
                    .ws = false,
            ),
            E(ENTITY_UNKNOWN, LOC("attribute-with-references.xml", 1, 44),
                    TOK("d"),
                    .type = XML_READER_REF_GENERAL,
                    .system_id = NULL,
                    .public_id = NULL,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 47),
                    TOK("e"),
                    .ws = false,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("\xD0\xAE"),
                    .ws = false,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 55),
                    TOK("g"),
                    .ws = false,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("\xD1\x8A"),
                    .ws = false,
            ),
            E(APPEND, LOC("attribute-with-references.xml", 1, 63),
                    TOK("h"),
                    .ws = false,
            ),
            E(STAG_END, LOC("attribute-with-references.xml", 1, 65),
                    NOTOK,
                    .is_empty = true,
            ),
            END,
        },
    },
    {
        TC("Attributes with invalid references"),
        .input = "attribute-invalid-references1.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("attribute-invalid-references1.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_0,
            ),
            E(STAG, LOC("attribute-invalid-references1.xml", 2, 1),
                    TOK("a"),
            ),
            E(ATTR, LOC("attribute-invalid-references1.xml", 2, 4),
                    TOK("b"),
                    .attrnorm = XML_READER_ATTRNORM_CDATA,
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 7),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Character reference did not evaluate to "
                    "a valid UCS-4 code point",
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 17),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Character reference did not evaluate to "
                    "a valid UCS-4 code point",
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 30),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Referenced character does not match Char production",
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 35),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Referenced character does not match Char production",
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 43),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Referenced character does not match Char production",
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 51),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Referenced character does not match Char production",
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 59),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_Reference),
                    .msg = "Malformed unknown reference",
            ),
            E(APPEND, LOC("attribute-invalid-references1.xml", 2, 60),
                    TOK(";"),
                    .ws = false,
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 61),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Malformed character reference",
            ),
            E(APPEND, LOC("attribute-invalid-references1.xml", 2, 63),
                    TOK(";"),
                    .ws = false,
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 64),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Malformed character reference",
            ),
            E(APPEND, LOC("attribute-invalid-references1.xml", 2, 67),
                    TOK(";"),
                    .ws = false,
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 68),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Malformed character reference",
            ),
            E(APPEND, LOC("attribute-invalid-references1.xml", 2, 71),
                    TOK("!"),
                    .ws = false,
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 72),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_EntityRef),
                    .msg = "Malformed general entity reference",
            ),
            E(APPEND, LOC("attribute-invalid-references1.xml", 2, 74),
                    TOK("^"),
                    .ws = false,
            ),
            E(MESSAGE, LOC("attribute-invalid-references1.xml", 2, 75),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CharRef),
                    .msg = "Referenced character does not match Char production",
            ),
            E(STAG_END, LOC("attribute-invalid-references1.xml", 2, 83),
                    NOTOK,
                    .is_empty = true,
            ),
            END,
        },
    },
    {
        TC("Attributes with references to restricted characters"),
        .input = "attribute-restricted-references.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(XMLDECL, LOC("attribute-restricted-references.xml", 1, 1),
                    NOTOK,
                    .encoding = NULL,
                    .standalone = XML_INFO_STANDALONE_NO_VALUE,
                    .version = XML_INFO_VERSION_1_1,
            ),
            E(STAG, LOC("attribute-restricted-references.xml", 2, 1),
                    TOK("a"),
            ),
            E(ATTR, LOC("attribute-restricted-references.xml", 2, 4),
                    TOK("b"),
                    .attrnorm = XML_READER_ATTRNORM_CDATA,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("\x01"),
                    .ws = false,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("\x1F"),
                    .ws = false,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("\x7F"),
                    .ws = false,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("\xC2\x80"),
                    .ws = false,
            ),
            E(STAG_END, LOC("attribute-restricted-references.xml", 2, 30),
                    NOTOK,
                    .is_empty = true,
            ),
            END,
        },
    },
    {
        TC("Character data with entity references"),
        .input = "chardata-entities.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("chardata-entities.xml", 1, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("chardata-entities.xml", 1, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(APPEND, LOC("chardata-entities.xml", 1, 4),
                    TOK("This is some text, with "),
                    .ws = false,
            ),
            E(ENTITY_START, LOC("chardata-entities.xml", 1, 28),
                    TOK("lt"),
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(ENTITY_END, LOC("chardata-entities.xml", 1, 32),
                    NOTOK,
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("<"),
                    .ws = false,
            ),
            E(APPEND, LOC("chardata-entities.xml", 1, 32),
                    TOK(" entities "),
                    .ws = false,
            ),
            E(ENTITY_START, LOC("chardata-entities.xml", 1, 42),
                    TOK("gt"),
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(ENTITY_END, LOC("chardata-entities.xml", 1, 46),
                    NOTOK,
                    .type = XML_READER_REF_INTERNAL,
            ),
            E(APPEND, LOC("entity(gt)", 1, 1),
                    TOK(">"),
                    .ws = false,
            ),
            E(APPEND, LOC("chardata-entities.xml", 1, 46),
                    TOK(" and "),
                    .ws = false,
            ),
            E(APPEND, LOC("character reference", 1, 1),
                    TOK("a"),
                    .ws = false,
            ),
            E(APPEND, LOC("chardata-entities.xml", 1, 57),
                    TOK(" "),
                    .ws = false,
            ),
            E(ENTITY_UNKNOWN, LOC("chardata-entities.xml", 1, 58),
                    TOK("custom"),
                    .type = XML_READER_REF_GENERAL,
            ),
            E(APPEND, LOC("chardata-entities.xml", 1, 66),
                    TOK(" entity."),
                    .ws = false,
            ),
            E(ETAG, LOC("chardata-entities.xml", 1, 74),
                    TOK("a"),
            ),
            END,
        },
    },
    {
        TC("CDATA section"),
        .input = "cdata.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("cdata.xml", 1, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("cdata.xml", 1, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(APPEND, LOC("cdata.xml", 1, 4),
                    TOK("A "),
                    .ws = false,
            ),
            E(CDSECT, LOC("cdata.xml", 1, 6),
                    TOK("section < with & special ]] characters inside"),
                    .ws = false,
            ),
            E(CDSECT, LOC("cdata.xml", 1, 63),
                    TOK(""),
                    .ws = false,
            ),
            E(CDSECT, LOC("cdata.xml", 1, 75),
                    TOK(" "),
                    .ws = false,
            ),
            E(APPEND, LOC("cdata.xml", 1, 88),
                    TOK("."),
                    .ws = false,
            ),
            E(ETAG, LOC("cdata.xml", 1, 89),
                    TOK("a"),
            ),
            END,
        },
    },
    {
        TC("Unterminated CDATA section"),
        .input = "unterminated-cdata.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(STAG, LOC("unterminated-cdata.xml", 1, 1),
                    TOK("a"),
            ),
            E(STAG_END, LOC("unterminated-cdata.xml", 1, 3),
                    NOTOK,
                    .is_empty = false,
            ),
            E(APPEND, LOC("unterminated-cdata.xml", 1, 4),
                    TOK("Unterminated "),
                    .ws = false,
            ),
            E(MESSAGE, LOC("unterminated-cdata.xml", XMLERR_EOF, XMLERR_EOF),
                    NOTOK,
                    .info = XMLERR(ERROR, XML, P_CDSect),
                    .msg = "Unterminated CDATA section",
            ),
            END,
        },
    },
    {
        TC("DTD (no subsets)"),
        .input = "dtd-no-subset.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(DTD_BEGIN, LOC("dtd-no-subset.xml", 1, 1),
                    TOK("a"),
            ),
            E(DTD_END, LOC("dtd-no-subset.xml", 1, 1),
                    NOTOK,
            ),
            E_EMPTY_A("dtd-no-subset.xml", 2, 1),
            END,
        },
    },
    {
        TC("DTD (external subset with SYSTEM id)"),
        .input = "dtd-ext-system.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(DTD_BEGIN, LOC("dtd-ext-system.xml", 1, 1),
                    TOK("a"),
            ),
            E(DTD_SYSID, LOC("dtd-ext-system.xml", 1, 1),
                    TOK("system.dtd"),
            ),
            E(DTD_END, LOC("dtd-ext-system.xml", 1, 1),
                    NOTOK,
            ),
            E_EMPTY_A("dtd-ext-system.xml", 2, 1),
            END,
        },
    },
    {
        TC("DTD (external subset with PUBLIC id)"),
        .input = "dtd-ext-public.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(DTD_BEGIN, LOC("dtd-ext-public.xml", 1, 1),
                    TOK("a"),
            ),
            E(DTD_PUBID, LOC("dtd-ext-public.xml", 1, 1),
                    TOK("-//Owner//Document//EN"),
            ),
            E(DTD_SYSID, LOC("dtd-ext-public.xml", 1, 1),
                    TOK("system.dtd"),
            ),
            E(DTD_END, LOC("dtd-ext-public.xml", 1, 1),
                    NOTOK,
            ),
            E_EMPTY_A("dtd-ext-public.xml", 2, 1),
            END,
        },
    },
    {
        TC("DTD (empty internal subset)"),
        .input = "dtd-int-empty.xml",
        .events = (const xml_reader_cbparam_t[]){
            E(DTD_BEGIN, LOC("dtd-int-empty.xml", 1, 1),
                    TOK("a"),
            ),
            E(DTD_INTERNAL, LOC("dtd-int-empty.xml", 1, 1),
                    NOTOK,
            ),
            E(DTD_END, LOC("dtd-int-empty.xml", 1, 1),
                    NOTOK,
            ),
            E_EMPTY_A("dtd-int-empty.xml", 2, 1),
            END,
        },
    },
};

static const testset_t testsets[] = {
    TEST_SET(run_testcase, "Various API tests", testcases_api),
    TEST_SET(run_testcase, "Encoding tests", testcases_encoding),
    TEST_SET(run_testcase, "XML/Text declaration tests", testcases_xmldecl),
    TEST_SET(run_testcase, "XML structures", testcases_structure),
};

static const testsuite_t testsuite = TEST_SUITE("Tests for XML reader API", testsets);

